### PR TITLE
BaselineOfMoose

### PR DESCRIPTION
**Pull request by sbragagnolo**
Modification of hte BaselineOfMoose: 

Extracts Roassal configuration to a BaselineOfRoassal
Extracts PetitParser configuration to a BaselineOfPetitParser
Extracts MooseIDE configuration to a BaselineOfMooseIDE
Extracts MooseFinder configuration to a BaselineOfMooseFinder
Extracts the "Additional tools" to BaselineOfMooseMiscs
Extracts Smacc configuration to a BaselineOfSmacc.

Refactor the existing groups to use the new configurations.
Adds new groups Allowing different configurations more oriented such as:
Core (Famix, fame, etc), 
CoreUI (Core+IDE+Finder), 
Java (core+ java smacc support), 
JavaUI (core+java smaccsupport+ide+finder+roassal), 
CoreSmacc (core+full smacc support) , 
CoreSmaccUI(core+fullsmacc support, IDE, finder, roassal), 
CorePetitParser (core+full petitparser support) , 
CorePetitParserUI (core+full petitparser support, IDE, Finder, roassal) , 
GraphicTools (Core, IDE, Finder, Miscs)
CoreParsers (Core, Smacc, PetitParser)
CoreParsersUI (Core, Smacc, PetitParser, Ide, Finder, roassal)

This allows to still loading the full version of moose, but also to versionate parts of moose with smacc / petitparser / roassal specific verisons.

### CODE REVIEW

**Comment by jecisc** [comment]
@sbragagnolo IMO MooseFinder and MooseIDE could be merged because they are both managing moose tools. What do you think?

**Comment by jecisc** [comment]
Pharo 8 jobs are broken. I'll try to relaunch them to see if it's random.

**Comment by jecisc** [comment]
No, still there. In Pharo 8 there is a failing test. But I don't know if it's linked to this PR of to a change in P8.

**Comment by badetitou** [comment]
The failing test is part of GLMRoassal2MorphicTest...

**Comment by jecisc** [comment]
It is not failing in other builds. Maybe packages are not loaded in the same order? This is weird.

**Comment by badetitou** [comment]
Ok... So the problem is that in pharo 8 the new baseline does not load 
"Glamour-Browsers-Pharo8"

**Comment by badetitou** [comment]
The tests are now all green (for Pharo 8 too)
Should we integrate @sbragagnolo @jecisc

**Comment by jecisc** [comment]
As I said IMO MooseFinder and MooseIDE should be merged. I was waiting to see if someone would agree/disagree on that. 

Except that, it's fine for me.

**Comment by badetitou** [comment]
Sorry, I just tried to fixed the bug, I didn't look at the other comments.

IMO the moose finder is part of the moose IDE so yes. I agree we can merge
into MooseIDE

Le mar. 9 juil. 2019 à 14:43, CyrilFerlicot <notifications@github.com> a
écrit :

**Comment by jecisc** [comment]
I also have a question, is that wanted to remove classes of XMLWriter core?

https://github.com/moosetechnology/Moose/pull/1605/commits/097d28fb7d667e90914f4c7707f54e750f778013

**Comment by jecisc** [comment]
I talked with Santi and it's not wanted. We should revert this change.

**Comment by jecisc** [comment]
@badetitou If it passes the tests, it's OK to merge in my opinion.

**Comment by badetitou** [comment]
Ok. Tests are green
I also fix some missing packages in baseline

**Pull request merged**
