### PR TITLE
Add the commit hash in the the Moose Help menu

### PR DESCRIPTION
**Pull request by badetitou**
This modification in the action and the Moose Help menu will add the build commit hash in the Moose Help Menu

Know issue:

- We have to re-open the Moose help menu. At startup, it shows a wrong commit number. Then, the correct one is used

commit

### CODE REVIEW

**Comment by badetitou** [comment]
(I propose to Squash and merge (no interest to keep all my test commit))

**Review by ClotildeToullec — APPROVED** [review]
Maybe we should open MooseWelcome only after updating MooseVersiont?
Like evaluating ```MooseVersion current commitHash: '$GITHUB_SHA'. HelpBrowser allInstances do: #close. mooseWelcome openForRelease.```?

**Comment by badetitou** [comment]
Yeah, probably the good way.. 
I should change again the baselineOfMoose and evaluate `HelpBrowser allInstances do: #close. mooseWelcome openForRelease` in the CI

**Comment by badetitou** [comment]
It should be ok now @ClotildeToullec

**Comment by badetitou** [comment]
commit

**Comment by ClotildeToullec** [comment]
Nice! Thank you!

**Comment by badetitou** [comment]
😄  @NicolasAnquetil

**Pull request merged**
