### PR TITLE
Famix CSharp Entities

### PR DESCRIPTION
**Pull request by sbragagnolo**
* Famix Csharp model 
* Famix Csharp model generator
* Adds FMTranslationUnit in it subclass flavors: Null, Dictionary and CopyReplace.
Adds tests and rewriting rules for the usage of #nameTranslator: / #nameTranslator . Both methods deprecated favoring a translationUnit:.message send (This setter and variable name changes has being changed for the sake of remarking the change on the semantic).

### CODE REVIEW

**Comment by badetitou** [comment]
Do we want to add CSharp inside Famix or as an external repository? 
IMO we should externalize things... 


Or if you really want @sbragagnolo maybe you can create an external repository and then we load your project by default in Moose.

What's your opinion @jecisc?

**Comment by fuhrmanator** [comment]
C Sharp should be like Java, to be consistent, right?

**Comment by badetitou** [comment]
I agree @fuhrmanator
But I'm not sure we should keep the Java metamodel inside the moose repository. 
I'm thinking of externalizing the metamodels, expect the abstract ones, but still load them in the image ( as we did with moose easy for example ) 

But, definitely CSharp should be like Java !

**Comment by jecisc** [comment]
I think we can accept the CSharp in Moose while we do not externalize the Java and Pharo MM. 

But in the long term, I would indeed like to have "Famix" "Famix-Java" "Famix-Pharo" "Famix-CSharp"...

**Comment by jecisc** [comment]
@sbragagnolo You have a new package but I don't see changes on baselines. 

Maybe to start splitting Famix we could have Famix-CSharp in another baseline?

**Comment by sbragagnolo** [comment]
@Benoît Verhaeghe <benoit.verhaeghe@inria.fr>
To me is the same really. I just put it on moose because Java is there as
well.
The requirement to have all in one repo is from Steph, all in the same repo
for being easily versionable (thing that will be truth meanwhile iceberg
does not support multiple project.. thing that does not seems happening any
time soon).

@Anne Etien <anne.etien@univ-lille.fr>
 this is a refactor and feature extension of a previously existing feature.
To have translations is key for being able to load MSE based on the old
famix model into the new famix models (Since they change the naming of the
classes).
 To me this is an intermediate step, pursuing the goal of getting a full
minimalistic csharp model.

@Cyril Ferlicot <cyril.ferlicot@gmail.com>
No I did not change any baseline. I will add a baseline for loading only it
self on testing.

**Comment by sbragagnolo** [comment]
Sorry the delay.

I think that is better to integrate, specially because of the fame
modification.  What goes to the Csharp model, it's going to change much
probably, but better to show that we are working actively on it.


Santiago

**Pull request merged**
