### PR TITLE
[WIP] Enable P12 in CI

### PR DESCRIPTION
**Pull request by jecisc**
Not to merge

I would like to see how moose behave in Pharo 11 VS Pharo 12 so I am doing a PR to enable P12 CI. This is not for merge purpose yet :)

### CODE REVIEW

**Comment by jecisc** [comment]
Tests are crahsing in P12 but the loading in itself is much faster in P12 than in P11 now!

**Comment by jecisc** [comment]
@ClotildeToullec It's green! 

Do you want to merge it and that I try to keep it green or do you prefer to keep the CI only on P11?

**Comment by ClotildeToullec** [comment]
Congrats! Err, maybe we wait until after the holidays? I will not be able to find much time if this suddently fails.

**Comment by jecisc** [comment]
@ClotildeToullec I got it green again. Do we merge?

**Comment by ClotildeToullec** [comment]
Yes!

**Pull request merged**
