### PR TITLE
update MM

### PR DESCRIPTION
**Pull request by badetitou**

### CODE REVIEW

**Comment by jecisc** [comment]
We already have this in FamixGenerator:

```
tNamed --|> #TWithModifiers.
```

Is it not enough?

**Comment by badetitou** [comment]
NO! we have to revert it!
I discussed about it with Anne

What if I want to have a named entity in my UI model? in my SQL model? in my AST model? 
It does not make sense to hve tNamed in FamixGenerator
It should be in another place (like OOGenerator)

Currently, this modification just breaks the other models

**Comment by jecisc** [comment]
Oh, I saw you added modifiers to named in java and smalltalk but not that you removed it in general generator. So it's fine with me.

**Comment by jecisc** [comment]
Also, even in OO everything named does not necessarily have a modifier. A pragma does not have one.

**Pull request merged**
