### PR TITLE
Retry PR 1524

### PR DESCRIPTION
**Pull request by guillep**
Annes' Changes  +  fix to make it green

### CODE REVIEW

**Comment by guillep** [comment]
Can you specify what changes? Because I got @anneetien also saying that you and @badetitou reverted changes of hers :)

**Comment by jecisc** [comment]
First the deletion of src-archive. It's hard to see more with all the changes.

What changes of @anneetien vanished? Because I do not remember we touched anything she did. @badetitou ? Requestion changes on PR with problems yes, reverting no.

**Comment by guillep** [comment]
I've removed src-archive, but there seem to be many strange changes with Roassal and StateSpecs. Any idea?

**Comment by badetitou** [comment]
For StateSpecs it looks like all the category has been rewritten?
from
`category: 'aString'` to `category: #'aString'` 
I do not know why. Is it a Pharo 8 thing?

For Roassal, It may be a bug with Windows end of line?

I think you should revert the Roassal one and keep the StateSpec

**Comment by badetitou** [comment]
done without the problem of Roassal and rc-archive https://github.com/moosetechnology/Moose/pull/1547

**Pull request closed without merging**
