### PR TITLE
2135-Why-TMethod-does-not-inherit-directly-from-namedEntity

### LINKED ISSUE #2135: Why TMethod does not inherit directly from namedEntity?
It's done in Pharo and Java indirectly through containerEntity. Cf issue #2134

### PR DESCRIPTION
**Pull request by ClotildeToullec**
Fix #2135 (and complete #2134)
Removed containerEntity from FamixJavaGenerator.
Now TMethod inherits directly from namedEntity and containerEntity is removed from Java and Pharo generators.

### CODE REVIEW

**Comment by jecisc** [comment]
This PR is in conflict after merging another. I'll see to fix it.

**Comment by jecisc** [comment]
Done.

**Comment by jecisc** [comment]
This PR does more than what is written in the title. It also removes FamixJavaContainer.

**Comment by anneetien** [comment]
Because things are intertwinned. So please accept the merge.

**Comment by jecisc** [comment]
This change seems wrong. It changes the parents of types from containers to scoping entities. Scoping entities are only Namespaces and Packages. But in Java it is possible to have inner classes.

**Pull request closed without merging**
