### PR TITLE
Improve-HashTable-comments

### PR DESCRIPTION
**Pull request by jecisc**
Add basic comments to HashTable classes.

### CODE REVIEW

**Comment by Ducasse** [comment]
Do we have tests for the HashTable?

**Comment by jecisc** [comment]
There is 80 tests

**Comment by Ducasse** [comment]
Cool!

**Comment by jecisc** [comment]
I talked to Marcus because maybe we can use this project to improve perf of Pharo when we have huge collections. (Might help for Lifeware)

**Pull request merged**
