### PR TITLE
2220-Change-Name-of-modifier-to-visibility-

### LINKED ISSUE #2220: Change Name of modifier to visibility
A visibility refers only to public, private, protected and so on.
Since each entity will have only one modifier, and not a collection, the way to access it should be changed (no more modifiers include:#toto).
Obviously, methods using modifier may eventually be modified consequently.

linked with #2098, #2121, #2202 and #2219.

### PR DESCRIPTION
**Pull request by mahugnon**
-  Rename modifiers into  visibility
- Change the type of visiblity for string and no more Set
- Modify isPackage, isProtected ...  methods consequently
- Move isAbtract from FamixTHasModifiers to FamixTClass  --> Resolve issue  #2219
- Modify Tests and resources consequently to make tests pass .  

fix #2220

### CODE REVIEW

**Comment by badetitou** [comment]
Under review

**Comment by jecisc** [comment]
What about #static #final? 

I know that Verveine put some "final" in the modifiers. 

I saw other parsers add the statics in those.

**Comment by jecisc** [comment]
IIRC C++ parser of Nicolas, it generates static, final and maybe others.

**Comment by anneetien** [comment]
We have to open an issue to manage them in an other way.

Anne

**Comment by jecisc** [comment]
Do we really want to manage it in another way? It will add more variables in multiple places and increase the memory consuption.

**Comment by NicolasAnquetil** [comment]
I think this is a good solution because it clarifies things. There is no reason to mix for example public, abstract or static in the same variable).

About VerveineJ: it exported what was asked by Famix and it will continue to do so. So if Famix changes, VerveineJ will change

About memory consumption: This is true that it will not be optimal, but it is a temporary situation. At some point, we will look at this more in depth in this issue. Probably using privateState (see also #2182)

**Comment by ClotildeToullec** [comment]
I'm closing this old issue. It has been fixed in Famix and is no longer up to date

**Pull request closed without merging**
