### PR TITLE
Add JSON importer and exporter

### PR DESCRIPTION
**Pull request by badetitou**
This is a JSON importer and exporter for FAME.

I added the main test for the importer and checked that the exporter produces correct JSON.

I know that more tests should be written for both the importer and the exporter, and since I am not a Parser expert a real one should take a look and create an optimized one (but this one is the first step and we can use it IMO to define some tests)

### CODE REVIEW

**Comment by Ducasse** [comment]
This is cool.
Do you save the type of the entity as an entry. 
Do you manage ref between entity like mse does?

I was tempted to use Ston for that and have a dumper (JSON) for the rest of the world.

**Comment by Ducasse** [comment]
I read the code and I have one question.
Why do you write a JSON parser and do not reuse the one of Sven. 
Then the importer job is to go from the parsed structures to FAMIX objects handling the refs to the same object. 
S.

**Comment by jecisc** [comment]
Fame already contains exporters and importers managing the information to export (for exporter) and the reconstruction of objects (for the importer). Both of those are using a strategy to manage the format. 

What Benoit did was to add those strategies for JSON which was the fastest solution to implement and the code that is not dependent on the syntax is common between both. 

If Benoit used a solution such as the JSON reader/writer he would probably need much more work to refactor the way Fame import/export is working.

**Comment by Ducasse** [comment]
Ok I tend to avoid to be forced to write parser by hand. Which I'm doing for the fluid class definition and is a pain. 
Do you mean that the MSE parser is mixing the reconstruction and parsing because normally these are two different phases: 1 I parse (FAMIXCLass (name ...) ) and second I create and object and associate refs and more. I should that we could simply change 1 and get 2 for free.

**Comment by jecisc** [comment]
We have one class that is parsing the syntax and one class managing the building of objects. 

But it is not done in two phases. The first class start to parse and when it finds something it gives it to the class responsible for the resolution then proceed with the parsing.

**Comment by Ducasse** [comment]
Ok then why we cannot hook the JSON parser of Sven? To me sven spent a lot of time making sure that his parser is rock solid.

**Comment by badetitou** [comment]
There is two things 

For the exporter : it was easy and do not really asked me a lot of work. 
I have tried to use the Json parser of Sven. But,(1) in moose you don't want to export everything, only some properties. The selection of those properties ( can be complex?) is already implemented in the Fame exporter. And (2) we can't directly the Sven json parser. We have to customize it.
So I decided ( also because of advices from Cyril) to use the Fame exporter and to simply defined a new printer. So we have three printer using one export. And I believe it is nice?

( Also, I do not want ston. I have created this exporter to be able to use moose with more tool and Json is currently one of the main format ( and use in my company )). 
But, I agree that Ston format should rock for us and other languages with a Ston parser. 

For the importer : 
I think my importer works with the Json produced by my exporter ( see test ). But I'm also pretty sure it didn't work with all Json files. And probably, using the one of Sven can be an easier way than developing again the parser.

The aim of this importer is to propose a first implementation so we can use it with the exporter. At the same time, we can create good test. 

I do not know how the generic Fame importer works. But, I suppose that we can optimize stuff because we are in a specific context ( importing moose model instead of a generic Json file ). And in such a case, I want to benefit from the optimization

( To answer the first questions, because I have used the standard famr importer and exporter I believe I handle everything as we did with mse ).

**Comment by badetitou** [comment]
I will rewrite this importer and exporter using a new JSON format. 
Probably the one in Graph DB (https://stackoverflow.com/questions/40532812/how-can-i-restore-data-from-a-previous-result-in-the-browser/40557891#40557891)

**Pull request merged**
