### PR TITLE
1580-Unknown-property-hasClassScope-in-FAMIXMethod

### LINKED ISSUE #1580: Unknown property 'hasClassScope' in FAMIXMethod
With the latest version of VerveineJ, there are messages while loading the MSE file:

> Unknown property 'hasClassScope' in FAMIXMethod

### PR DESCRIPTION
**Pull request by badetitou**
add compatibility property hasClassScope

fixes #1580

### CODE REVIEW

**Comment by jecisc** [comment]
@badetitou should it be deprecated?

**Comment by badetitou** [comment]
> @badetitou should it be deprecated?

Yes... I mean... The compatibility model is deprecated

**Comment by badetitou** [comment]
@jecisc I've added the deprecated method (withTransform:)
Do you think it is enough? Another idea?

**Comment by jecisc** [comment]
Yes!

**Pull request merged**
