### PR TITLE
2136-Why-has-NamedEntity-a-modifier-

### LINKED ISSUE #2136: Why has NamedEntity a modifier ?
Packages don't have modifiers.
C function neither.

### PR DESCRIPTION
**Pull request by ClotildeToullec**
Fix #2136
Removed #THasModifiers from namedEntity in FamixPharoSmalltalkGenerator

### CODE REVIEW

**Comment by jecisc** [comment]
It now have a conflict. I'll see to fix it.

**Comment by jecisc** [comment]
Conflict fixed. Now let's the CI run again.

**Comment by jecisc** [comment]
This PR does more than what is written in the title. It also removes FamixJavaContainer.

**Comment by anneetien** [comment]
Because things were intertwinned (related to other issues we already closed). So it would be great to accept it.

**Comment by jecisc** [comment]
This change seems wrong. It changes the parents of types from containers to scoping entities. Scoping entities are only Namespaces and Packages. But in Java it is possible to have inner classes.

**Comment by badetitou** [comment]
done here #2199

**Comment by anneetien** [comment]
Normally, a scopingEntity is an entity with a Scope. I remember discussion with Nicolas saying that a Class is a Scoping Entity.  Perhaps we should discuss that also.

**Comment by jecisc** [comment]
Maybe, but in that case the good use of Scoping entity should be done before the removal of containers.

**Pull request closed without merging**
